### ISSUE TITLE
Is this the primary source for libslink?

### ISSUE THREAD

**Issue by paride** [iris-edu/slinktool#2]
Not really an issue, just a question: should this package be considered the main upstream source for `libslink`? Or is the library developed somewhere else and then just imported here? Thank you.

**Comment by chad-earthscope** [comment]
@paride No, `libslink` is a separate project and is included in many other repositories.  Currently there is no public facing repository for `libslink`, but I'll get it here on GitHub as soon as I have time.

**Comment by paride** [comment]
Thanks @chad-iris, I'll keep an eye on the `iris-edu` repositories.
